In [12]:
# Helper functions to load pickled data 
from load_help import load_encodings
from load_help import load_decodings
from load_help import load_training
from load_help import load_testing

# Helper functions to handle sentences 
from experiments import decode
from experiments import encode_sentence
from experiments import decode_sentence

import cfg
import networks 
from importlib import reload
reload(networks)
reload(networks)

decodings = load_decodings()
encodings = load_encodings()

# Generate test sentence
corpus = cfg.create_corpus(1)
sentence = corpus[0]
inputs = encode_sentence(sentence)

num_words = len(encodings)
architecture = [num_words, 10, num_words]

test = networks.RNN(architecture)
test.evaluate(inputs)

([array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]),
  array([-0.75239014, -0.48076763, -0.5207496 , -0.52857098, -0.67816669,
         -0.63513483, -0.4319956 , -0.20880006, -0.72680126, -0.60219613]),
  array([ 0.95814774,  0.99158536,  0.99726496,  0.99434867,  0.99165547,
          0.95729338,  0.99654249,  0.97766335,  0.9914898 ,  0.967347  ]),
  array([-0.9998658 , -0.99997334, -0.99999598, -0.99998769, -0.99999715,
         -0.99991558, -0.99999605, -0.99996277, -0.99999622, -0.99997646]),
  array([ 0.99946003,  0.99990934,  0.99998581,  0.99995358,  0.99997566,
          0.99937835,  0.99997639,  0.99967912,  0.99997451,  0.99952117]),
  array([-0.99987531, -0.99998668, -0.99999912, -0.99999465, -0.99999801,
         -0.99995687, -0.99999302, -0.99995185, -0.99999868, -0.99996931])],
 [array([ 0.99271036,  0.99462241,  0.96501701,  0.98558133,  0.98626243,
          0.98500421,  0.99664995,  0.98769452,  0.99467551,  0.99867098,
          0.99744451,  0.99685213,  0.99

In [12]:
import numpy as np

t = np.matrix([100,2])
print(np.tanh(t))

[[ 1.          0.96402758]]
